baseURL: http://something-fresh.org/
languageCode: en-us
title: Empresta.me
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/bee.svg
    link: /
    # Default width/height. Uncomment if you need to change
    #width: 70
    #height: 60 # ----doesnt work (probably the navbar has its own limit)
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Empresta.me
    # Hero subtitle (optional)
    subtitle: Really cool slogan like idk mess with bees, get shot in the knees
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/honeycomb.svg
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    #clientlogos: # ----were not using these, they're still here just in case they may come in usefull
    #- logo: systek
    #  url: https://google.com
    #- logo: tribe
    #  url: https://stefma.github.io/hugo-fresh/
    #- logo: kromo
    #  url: https://github.com/StefMa/hugo-fresh
    #- logo: infinite
    #  url: https://hugo-fresh.vercel.app/
    #- logo: gutwork
    #  url: https://bulma.io/
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Documentation
    url: /
  - title: Source Code
    url: https://github.com/Empresta-me/
  #- title: Dropdown
  #  sublinks:
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  #  - title: Dropdown item
  #    url: /
  - title: Dark Mode
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: Project
    subtitle: | # < this thingy should keep the break lines, I have no ideia why its all in a single paragraph
      Empresta.me is a modern application used to share items with anyone.
      With a simple interface, our users can easily connect with people around them to lend and borrow items they're needing.
      And, thanks to our Vouch Reputation System, without ever doubting if the person is trustworthy.
    tiles:
    - title: Demo
      icon: mouse-globe
      url: /
      buttonText: Try it On
      text: (In progress)
    - title: Poster
      icon: laptop-cloud
      url: /
      buttonText: Check it Out
      text: (In progress)
  section2:
    title: About our app
    subtitle: the beest in the world
    features:
    - title: Context
      text: |
        Consumption has been rising and everything is getting more expensive each day that passes.
        More than ever are people looking for other ways of fullfiling their needs without having to buy things.
        We can't (or rather shouldn't) help stealing... So were foccusing on sharing :)
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Problem
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Goal
      text: 
      icon: mobile-feed
  section3:
    title: Calendar
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Meet our Team
    #subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    orientorClients:
    - name: André Zuquete
      job: Supervisor
      img: 3
    clients:
    - name: Bruno Moura
      job: Backend Developer
      img: 1
    - name: João Teles
      job: Backend Developer
      img: 2
    moreClients:
    - name: Inês Castro
      job: Team Leader
      img: 3
    - name: Rafael Remígio
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Android Dev
      img: 1
    - name: Diogo Silva
      job: DevOps Master
      img: 2

  section5:
    title: Drop us a line or two
    subtitle: We'd love to hear from you
    buttonText: Send Message
    # action: https://formspree.io/f/<form_id>
    # method: POST
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
